<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>SpaceSnoop.Wpf</RootNamespace>
    <AssemblyName>SpaceSnoop.Wpf</AssemblyName>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpaceSnoop.Core\SpaceSnoop.Core.csproj" />
    <PackageReference Include="KeepShell" Version="0.1.19" />
    <PackageReference Include="KeepShell.Themes.Tarkov" Version="0.1.19" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="MahApps.Metro.IconPacks.Lucide" Version="6.2.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Tomlyn" Version="2.4.0" />
  </ItemGroup>

</Project>
