name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    if: github.repository == 'MaxNagibator/SpaceSnoop'

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on:
      labels: BobGroupWindowsServer

    env:
      Solution_Name: SpaceSnoop.sln
      Test_Project_Path: SpaceSnoop\SpaceSnoop.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Publish
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true
      

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-forms-app
        path: bin/Release/net10.0-windows/win-x64/publish/
